// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAatQpVuX2queo863PU0rASljlcj8bM7mM',
    appId: '1:982914815070:web:fba90d1aef910e27be10cf',
    messagingSenderId: '982914815070',
    projectId: 'bcaproject-a89d4',
    authDomain: 'bcaproject-a89d4.firebaseapp.com',
    storageBucket: 'bcaproject-a89d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCwEq-KA9emzdHYcaqz1cLF6zRqnOvJA',
    appId: '1:982914815070:android:350756550ba0ca5ebe10cf',
    messagingSenderId: '982914815070',
    projectId: 'bcaproject-a89d4',
    storageBucket: 'bcaproject-a89d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDquCy_z2MMtTeRkobvXappdz4ixddt-as',
    appId: '1:982914815070:ios:6168196d1df888c9be10cf',
    messagingSenderId: '982914815070',
    projectId: 'bcaproject-a89d4',
    storageBucket: 'bcaproject-a89d4.appspot.com',
    iosBundleId: 'com.example.greenvillabca',
  );
}
